# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\demo_testcase_ref.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest ,RunTestCase
from testcases.login_testcase import TestCaseLoginTestcaseRef as login


class TestCaseUserTestcaseRef(HttpRunner):

    config = (
        Config("request methods testcase: reference testcase")
        .base_url("https://qyapi.weixin.qq.com")
        .verify(False)
        .export("access_token")
    )

    teststeps = [
        Step(
            RunTestCase("获取access_token")
                .with_variables()
                .call(login)
                .export("access_token")
        ),
        Step(
            RunRequest("创建用户")
                .post("/cgi-bin/user/create")
                .with_params(**{"access_token": "$access_token"})
                .with_json("${user_data(all)}")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.errcode", 0)
        ),
        Step(
            RunRequest("修改用户")
                .post("/cgi-bin/user/update")
                .with_params(**{"access_token": "$access_token"})
                .with_json("${user_data(all)}")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.errcode", 0)
        ),
        Step(
            RunRequest("读取用户")
                .get("/cgi-bin/user/get")
                .with_params(**{"access_token": "$access_token", "userid": "${user_data(userid)}"})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.errcode", 0)
                .assert_equal("body.errmsg", "ok")
        ),
        Step(
            RunRequest("删除用户")
            .get("/cgi-bin/user/delete")
            .with_params(**{"access_token": "$access_token", "userid":"${user_data(userid)}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.errcode", 0)
            .assert_equal("body.errmsg", "deleted")
        ),
    ]

if __name__ == "__main__":
    TestCaseUserTestcaseRef().test_start()
