# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\demo_testcase_ref.yml

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseLoginTestcaseRef(HttpRunner):
    config = (
        Config("request methods testcase: reference testcase")
            .base_url("https://qyapi.weixin.qq.com")
            .verify(False)
            .export("access_token")
    )

    teststeps = [
        Step(
            RunRequest("获得token")
                .get("/cgi-bin/gettoken")
                .with_params(
                **{"corpsecret": "zHiVxtcvQwte9XtJ5ITpYCqSxoO_PUwc6l2t9DR_6d4", "corpid": "ww257577244a96bd33"})
                .extract()
                .with_jmespath("body.access_token", "access_token")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.errmsg", "ok")
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginTestcaseRef().test_start()
