# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\demo_testcase_ref.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest ,RunTestCase
from testcases.login_testcase import TestCaseLoginTestcaseRef as login
from testcases.department_test.basic.department_create_testcase import TestCaseDepartmentCreateTestcaseRef as dept_crate
from testcases.department_test.basic.department_delete_testcase import TestCaseDepartmentCreateTestcaseRef as dept_delete


class TestCaseDepartmentIdTestcaseRef(HttpRunner):

    config = (
        Config("request methods testcase: reference testcase")
        .base_url("https://qyapi.weixin.qq.com")
        .verify(False)
        .export("access_token")
    )

    teststeps = [
        Step(
            RunTestCase("获取access_token")
                .call(login)
        ),
        Step(
            RunTestCase("创建部门")
                .call(dept_crate)
        ),
        Step(
            RunRequest("更新部门")
                .post("/cgi-bin/department/update")
                .with_params(**{"access_token": "$access_token"})
                .with_json({
                "id": 1000,
                "name": "${user_data(name)}",
            })
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.errcode", 60003)
        ),
        Step(
            RunTestCase("删除部门")
                .call(dept_delete)
        ),
    ]

if __name__ == "__main__":
    TestCaseDepartmentIdTestcaseRef().test_start()
