# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\demo_testcase_ref.yml
# 冒烟用例


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest ,RunTestCase
from testcases.login_testcase import TestCaseLoginTestcaseRef as login


class TestCaseLabelTestcaseRef(HttpRunner):

    config = (
        Config("request methods testcase: reference testcase")
        .base_url("https://qyapi.weixin.qq.com")
        .verify(False)
        .export("access_token")
    )

    teststeps = [
        Step(
            RunTestCase("获取access_token")
                .with_variables()
                .call(login)
                .export("access_token")
        ),
        Step(
            RunRequest("创建标签")
                .post("/cgi-bin/tag/create")
                .with_params(**{"access_token": "$access_token"})
                .with_json("${tag_data(all)}")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.errcode", 0)
        ),
        Step(
            RunRequest("更新标签")
                .post("/cgi-bin/tag/update")
                .with_params(**{"access_token": "$access_token"})
                .with_json("${tag_data(all)}")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.errcode", 0)
        ),
        Step(
            RunRequest("读取标签")
                .get("/cgi-bin/tag/get")
                .with_params(**{"access_token": "$access_token","tagid":"${tag_data(tagid)}"})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.errcode", 0)
                .assert_equal("body.errmsg", "ok")
        ),
        Step(
            RunRequest("删除标签")
            .get("/cgi-bin/tag/delete")
            .with_params(**{"access_token": "$access_token", "tagid":"${tag_data(tagid)}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.errcode", 0)
            .assert_equal("body.errmsg", "deleted")
        ),
    ]

if __name__ == "__main__":
    TestCaseLabelTestcaseRef().test_start()
